import pptxgen from "pptxgenjs";

export interface SlideData {
  title: string;
  subtitle?: string;
  bulletPoints?: string[];
  keyTakeaway?: string;
  speakerNotes?: string;
}

export interface PresentationData {
  topic: string;
  slides: SlideData[];
}

export function cleanMarkdownText(str: string): string {
  if (!str) return "";
  return str
    .replace(/<[^>]*>/g, "") // Remove HTML tags like <mark>, <span>
    .replace(/#{1,6}\s*/g, "") // Remove ###, ##, # header markers
    .replace(/\*\*(.*?)\*\*/g, "$1") // Remove **bold**
    .replace(/\*(.*?)\*/g, "$1") // Remove *italic*
    .replace(/`{1,3}(.*?)(`{1,3}|$)/g, "$1") // Remove code backticks
    .replace(/\[(.*?)\]\(.*?\)/g, "$1") // Remove markdown links
    .replace(/^[\s\-\*\•\d\.\)]+/g, "") // Remove leading dashes/bullet numbers
    .trim();
}

export async function generatePptxFile(presentation: PresentationData): Promise<void> {
  const pptx = new pptxgen();

  const cleanTopic = cleanMarkdownText(presentation.topic) || "Presentation";

  pptx.layout = "LAYOUT_16x9";
  pptx.author = "QuickSolv AI";
  pptx.company = "QuickSolv Engine";
  pptx.title = cleanTopic;

  const shapeType = pptx.ShapeType;

  // Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "111827" }; // Slate Dark Modern Theme

  // Accent Line
  titleSlide.addShape(shapeType.rect, {
    x: 0.8,
    y: 1.8,
    w: 0.15,
    h: 3.2,
    fill: { color: "F59E0B" }
  });

  titleSlide.addText(cleanTopic.toUpperCase(), {
    x: 1.2,
    y: 1.8,
    w: 11.0,
    h: 1.8,
    fontFace: "Arial",
    fontSize: 34,
    bold: true,
    color: "FFFFFF",
    align: "left",
    valign: "middle"
  });

  titleSlide.addText("Professional Presentation Generated by QuickSolv AI", {
    x: 1.2,
    y: 3.6,
    w: 10.0,
    h: 0.6,
    fontFace: "Arial",
    fontSize: 18,
    color: "D1D5DB",
    align: "left"
  });

  titleSlide.addText(`Date: ${new Date().toLocaleDateString()} | Total Slides: ${presentation.slides.length}`, {
    x: 1.2,
    y: 4.8,
    w: 10.0,
    h: 0.5,
    fontFace: "Arial",
    fontSize: 12,
    color: "9CA3AF"
  });

  // Individual Content Slides
  presentation.slides.forEach((slideData, idx) => {
    const slide = pptx.addSlide();
    slide.background = { color: "F9FAFB" };

    const slideTitle = cleanMarkdownText(slideData.title) || `Slide ${idx + 1}`;
    const slideSubtitle = cleanMarkdownText(slideData.subtitle || "");
    const slideTakeaway = cleanMarkdownText(slideData.keyTakeaway || "");

    // Top Header Banner
    slide.addShape(shapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 1.1,
      fill: { color: "1F2937" }
    });

    slide.addText(`${idx + 1}. ${slideTitle}`, {
      x: 0.6,
      y: 0.2,
      w: 12.0,
      h: 0.7,
      fontFace: "Arial",
      fontSize: 22,
      bold: true,
      color: "FFFFFF",
      valign: "middle"
    });

    // Subtitle if available
    if (slideSubtitle) {
      slide.addText(slideSubtitle, {
        x: 0.6,
        y: 1.3,
        w: 12.0,
        h: 0.4,
        fontFace: "Arial",
        fontSize: 14,
        italic: true,
        color: "4B5563"
      });
    }

    // Bullet points container
    if (slideData.bulletPoints && slideData.bulletPoints.length > 0) {
      const cleanBullets = slideData.bulletPoints
        .map(pt => cleanMarkdownText(pt))
        .filter(pt => pt.length > 0)
        .map(cleanPt => ({
          text: cleanPt,
          options: { fontSize: 15, color: "1F2937", spaceAfter: 12 }
        }));

      if (cleanBullets.length > 0) {
        slide.addText(cleanBullets, {
          x: 0.6,
          y: slideSubtitle ? 1.8 : 1.5,
          w: slideTakeaway ? 7.8 : 12.0,
          h: 4.6,
          fontFace: "Arial",
          bullet: { type: "number" },
          valign: "top"
        });
      }
    }

    // Key Takeaway Card (Side Card)
    if (slideTakeaway) {
      slide.addShape(shapeType.roundRect, {
        x: 8.8,
        y: 1.5,
        w: 4.0,
        h: 4.8,
        fill: { color: "FEF3C7" },
        line: { color: "F59E0B", width: 1.5 }
      });

      slide.addText("KEY TAKEAWAY", {
        x: 9.0,
        y: 1.7,
        w: 3.6,
        h: 0.4,
        fontFace: "Arial",
        fontSize: 14,
        bold: true,
        color: "92400E"
      });

      slide.addText(slideTakeaway, {
        x: 9.0,
        y: 2.2,
        w: 3.6,
        h: 3.8,
        fontFace: "Arial",
        fontSize: 13,
        color: "78350F",
        valign: "top"
      });
    }

    // Speaker notes
    if (slideData.speakerNotes) {
      slide.addNotes(cleanMarkdownText(slideData.speakerNotes));
    }

    // Footer
    slide.addText(`QuickSolv AI • ${cleanTopic}`, {
      x: 0.6,
      y: 7.0,
      w: 8.0,
      h: 0.3,
      fontFace: "Arial",
      fontSize: 10,
      color: "9CA3AF"
    });

    slide.addText(`${idx + 1} / ${presentation.slides.length}`, {
      x: 11.5,
      y: 7.0,
      w: 1.2,
      h: 0.3,
      fontFace: "Arial",
      fontSize: 10,
      color: "9CA3AF",
      align: "right"
    });
  });

  // Save presentation
  const fileName = `${cleanTopic.replace(/[^a-zA-Z0-9]/g, "_")}_Presentation.pptx`;
  await pptx.writeFile({ fileName });
}
