import pptxgen from "pptxgenjs";

export interface SlideData {
  title: string;
  subtitle?: string;
  bulletPoints?: string[];
  keyTakeaway?: string;
  speakerNotes?: string;
}

export interface PresentationData {
  topic: string;
  slides: SlideData[];
}

export async function generatePptxFile(presentation: PresentationData): Promise<void> {
  const pptx = new pptxgen();

  pptx.layout = "LAYOUT_16x9";
  pptx.author = "QuickSolv AI";
  pptx.company = "QuickSolv Engine";
  pptx.title = presentation.topic;

  const shapeType = pptx.ShapeType;

  // Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "1E1B18" }; // Dark elegant theme

  // Gold/Amber accent line
  titleSlide.addShape(shapeType.rect, {
    x: 0.8,
    y: 1.8,
    w: 0.15,
    h: 3.2,
    fill: { color: "D97706" }
  });

  titleSlide.addText(presentation.topic.toUpperCase(), {
    x: 1.2,
    y: 1.8,
    w: 11.0,
    h: 1.8,
    fontFace: "Arial",
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    align: "left",
    valign: "middle"
  });

  titleSlide.addText("Interactive Presentation Generated by QuickSolv AI", {
    x: 1.2,
    y: 3.6,
    w: 10.0,
    h: 0.6,
    fontFace: "Arial",
    fontSize: 18,
    color: "D1D5DB",
    align: "left"
  });

  titleSlide.addText(`Date: ${new Date().toLocaleDateString()} | Total Slides: ${presentation.slides.length}`, {
    x: 1.2,
    y: 4.8,
    w: 10.0,
    h: 0.5,
    fontFace: "Arial",
    fontSize: 12,
    color: "9CA3AF"
  });

  // Individual Content Slides
  presentation.slides.forEach((slideData, idx) => {
    const slide = pptx.addSlide();
    slide.background = { color: "FAFAFA" };

    // Top Header Banner
    slide.addShape(shapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 1.1,
      fill: { color: "4A2711" }
    });

    slide.addText(`Slide ${idx + 1}: ${slideData.title}`, {
      x: 0.6,
      y: 0.2,
      w: 12.0,
      h: 0.7,
      fontFace: "Arial",
      fontSize: 22,
      bold: true,
      color: "FFFFFF",
      valign: "middle"
    });

    // Subtitle if available
    if (slideData.subtitle) {
      slide.addText(slideData.subtitle, {
        x: 0.6,
        y: 1.3,
        w: 12.0,
        h: 0.4,
        fontFace: "Arial",
        fontSize: 14,
        italic: true,
        color: "4B5563"
      });
    }

    // Bullet points container
    if (slideData.bulletPoints && slideData.bulletPoints.length > 0) {
      const bullets = slideData.bulletPoints.map(point => ({
        text: point,
        options: { fontSize: 15, color: "1F2937", spaceAfter: 12 }
      }));

      slide.addText(bullets, {
        x: 0.6,
        y: slideData.subtitle ? 1.8 : 1.5,
        w: slideData.keyTakeaway ? 7.8 : 12.0,
        h: 4.5,
        fontFace: "Arial",
        bullet: { type: "number" },
        valign: "top"
      });
    }

    // Key Takeaway Card (Side Card)
    if (slideData.keyTakeaway) {
      slide.addShape(shapeType.roundRect, {
        x: 8.8,
        y: 1.5,
        w: 4.0,
        h: 4.8,
        fill: { color: "FEF3C7" },
        line: { color: "F59E0B", width: 1.5 }
      });

      slide.addText("💡 KEY TAKEAWAY", {
        x: 9.0,
        y: 1.7,
        w: 3.6,
        h: 0.4,
        fontFace: "Arial",
        fontSize: 14,
        bold: true,
        color: "92400E"
      });

      slide.addText(slideData.keyTakeaway, {
        x: 9.0,
        y: 2.2,
        w: 3.6,
        h: 3.8,
        fontFace: "Arial",
        fontSize: 13,
        color: "78350F",
        valign: "top"
      });
    }

    // Footer
    slide.addText(`QuickSolv AI • ${presentation.topic}`, {
      x: 0.6,
      y: 7.0,
      w: 8.0,
      h: 0.3,
      fontFace: "Arial",
      fontSize: 10,
      color: "9CA3AF"
    });

    slide.addText(`${idx + 1} / ${presentation.slides.length}`, {
      x: 11.5,
      y: 7.0,
      w: 1.2,
      h: 0.3,
      fontFace: "Arial",
      fontSize: 10,
      color: "9CA3AF",
      align: "right"
    });
  });

  // Save presentation
  const fileName = `${presentation.topic.replace(/[^a-zA-Z0-9]/g, "_")}_Presentation.pptx`;
  await pptx.writeFile({ fileName });
}
