import { GeminiStudyResponse, cleanJsonResponse } from "./gemini";

export interface OxAlphaOptions {
  prompt: string;
  mode?: string;
  modelOverride?: string;
  apiKey?: string;
  userName?: string;
  history?: Array<{ role: "user" | "assistant"; content: string }>;
  image?: { mimeType: string; data: string };
  pdf?: { mimeType: string; data: string };
}

const OPENROUTER_FALLBACK_MODELS = [
  "openai/gpt-4o",
  "google/gemini-2.5-flash",
  "meta-llama/llama-3.3-70b-instruct:free",
  "openai/gpt-4o-mini"
];

export async function generateOxAlphaContent(options: OxAlphaOptions): Promise<GeminiStudyResponse> {
  const apiKey =
    options.apiKey ||
    process.env.OX_ALPHA_API_KEY ||
    process.env.OPENROUTER_API_KEY ||
    "";

  const requestedModel = options.modelOverride && options.modelOverride !== "ox-alpha" ? options.modelOverride : "openai/gpt-4o";
  const candidateModels = Array.from(new Set([requestedModel, ...OPENROUTER_FALLBACK_MODELS]));
  const userName = options.userName || "User";

  const systemInstruction = `You are QuickSolv powered by Main Ox Alpha Real AI Engine (OpenAI GPT-4o Engine), a world-class universal AI solution engine.
The user's name is ${userName}.

ZERO FIXED RESPONSE TEMPLATE:
- Respond dynamically based on the exact user request.
- Solve the user's actual problem with accuracy and actionable next steps.
- Use cool emoji headings (NO numbered headings like ## 1.).
- Highlight critical takeaways with yellow <mark> tags and main helpful points with blue <span style="color: #2563eb;"> tags.

Return your response as a valid JSON object matching:
{
  "subject": "Subject Name",
  "topic": "Topic Name",
  "difficulty": "Easy, Medium, or Hard",
  "quick_answer": "Direct concise answer",
  "easy_explanation": "Simple clear explanation",
  "normal_solution": "Complete step-by-step solution",
  "important_points": ["Key takeaway 1", "Key takeaway 2"],
  "quiz": [
    { "question": "Question text", "options": ["A", "B", "C", "D"], "correct_answer": "A", "explanation": "Why correct" }
  ],
  "confidence": "High"
}`;

  const messages: any[] = [{ role: "system", content: systemInstruction }];

  if (options.history && options.history.length > 0) {
    const recent = options.history.slice(-6);
    for (const h of recent) {
      let content = h.content;
      if (h.role === "assistant") {
        try {
          const parsed = JSON.parse(h.content);
          content = parsed.quick_answer || parsed.normal_solution || h.content;
        } catch {}
      }
      messages.push({
        role: h.role === "assistant" ? "assistant" : "user",
        content: content.length > 800 ? content.substring(0, 800) + "..." : content
      });
    }
  }

  messages.push({ role: "user", content: options.prompt });

  let lastError: any = null;

  for (const model of candidateModels) {
    try {
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://quicksolv.app",
          "X-Title": "QuickSolv AI Engine",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: model,
          messages: messages,
          temperature: 0.2,
          max_tokens: 3000,
          response_format: { type: "json_object" }
        })
      });

      if (!response.ok) {
        const errText = await response.text();
        console.warn(`OxAlpha model '${model}' failed status ${response.status}: ${errText}`);
        lastError = new Error(`Status ${response.status}: ${errText}`);
        continue;
      }

      const data = await response.json();
      const rawText = data.choices?.[0]?.message?.content || "";
      const cleanedText = cleanJsonResponse(rawText);
      const parsed: GeminiStudyResponse = JSON.parse(cleanedText);
      return parsed;
    } catch (err: any) {
      console.warn(`OxAlpha call attempt with model '${model}' failed:`, err.message);
      lastError = err;
    }
  }

  console.error("All OxAlpha model candidates failed, calling raw fallback:", lastError);
  const rawFallback = await generateRawOxAlphaText(options.prompt, apiKey);
  return {
    subject: "OxAlpha AI",
    topic: options.prompt.substring(0, 30),
    difficulty: "Medium",
    quick_answer: rawFallback.substring(0, 150),
    easy_explanation: "Direct response generated by Real OxAlpha API.",
    normal_solution: rawFallback,
    formulas: [],
    examples: [],
    exam_answer: {},
    memory_trick: "",
    common_mistakes: [],
    important_points: ["OxAlpha Real API Active"],
    quiz: [],
    confidence: "High"
  };
}

export async function generateRawOxAlphaText(prompt: string, apiKeyOverride?: string): Promise<string> {
  const apiKey =
    apiKeyOverride ||
    process.env.OX_ALPHA_API_KEY ||
    process.env.OPENROUTER_API_KEY ||
    "";

  const candidateModels = ["openai/gpt-4o", "google/gemini-2.5-flash", "meta-llama/llama-3.3-70b-instruct:free"];
  let lastNotice = "";

  for (const model of candidateModels) {
    try {
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://quicksolv.app",
          "X-Title": "QuickSolv AI Engine",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: model,
          messages: [
            { role: "system", content: "You are QuickSolv OxAlpha, a highly capable AI assistant. Answer directly, accurately, and naturally." },
            { role: "user", content: prompt }
          ],
          temperature: 0.3,
          max_tokens: 3000
        })
      });

      if (!response.ok) {
        const errText = await response.text();
        lastNotice = `OxAlpha API Notice (${response.status}): ${errText}`;
        continue;
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content;
      if (content) return content;
    } catch (err: any) {
      console.warn(`generateRawOxAlphaText model '${model}' failed:`, err);
      lastNotice = `OxAlpha API Connection Error: ${err.message || "Failed to reach OpenRouter"}`;
    }
  }

  return lastNotice || "No response generated by OxAlpha API.";
}

